import { FormEvent, useEffect, useState } from 'react';
import { AlertTriangle, PackagePlus, Save, Trash2 } from 'lucide-react';
import { api, type Category, type Product } from '@/services/api';

const empty = { name: '', slug: '', category: '', price: '', oldPrice: '', stock: '', unit: '1 unit', image: '', description: '', organic: false };

export function InventoryManager({ onChanged }: { onChanged: () => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]);
  const [form, setForm] = useState(empty); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const load = () => api.getAdminProducts().then(setProducts);
  useEffect(() => { load(); api.getCategories().then(setCategories); }, []);
  const create = async (e: FormEvent) => { e.preventDefault(); setSaving(true); setMessage(''); try {
    await api.createProduct({ ...form, price: Number(form.price), oldPrice: form.oldPrice ? Number(form.oldPrice) : undefined, stock: Number(form.stock), deliveryMins: 30, description: form.description || 'Fresh DairyXpress product' });
    setForm(empty); setMessage('Product added successfully.'); load(); onChanged();
  } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not add product.'); } finally { setSaving(false); } };
  const update = async (p: Product, values: { stock: number; price: number; oldPrice?: number }) => { setSaving(true); try { await Promise.all([api.updateStock(p.id, values.stock), api.updatePricing(p.id, values.price, values.oldPrice)]); await load(); onChanged(); setMessage(`${p.name} updated.`); } finally { setSaving(false); } };
  const remove = async (p: Product) => { if (!window.confirm(`Delete ${p.name}?`)) return; setSaving(true); try { await api.deleteProduct(p.id); await load(); onChanged(); setMessage(`${p.name} deleted.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not delete product.'); } finally { setSaving(false); } };
  return <section className="mt-6 rounded-4xl bg-white p-6 shadow-card"><div className="flex items-center gap-2"><PackagePlus className="h-5 w-5 text-primary"/><h2 className="font-heading text-lg font-bold text-ink">Product & inventory management</h2></div>
    <form onSubmit={create} className="mt-5 grid gap-3 md:grid-cols-4"><input required placeholder="Product name" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value,slug:f.slug||e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}))} className="input-premium"/><input required placeholder="URL slug" value={form.slug} onChange={e=>setForm(f=>({...f,slug:e.target.value}))} className="input-premium"/><select required value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value}))} className="input-premium"><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select><input required placeholder="Unit (e.g. 1 L)" value={form.unit} onChange={e=>setForm(f=>({...f,unit:e.target.value}))} className="input-premium"/>
      <input required min="0" step="0.01" type="number" placeholder="Selling price" value={form.price} onChange={e=>setForm(f=>({...f,price:e.target.value}))} className="input-premium"/><input min="0" step="0.01" type="number" placeholder="Original price (discount)" value={form.oldPrice} onChange={e=>setForm(f=>({...f,oldPrice:e.target.value}))} className="input-premium"/><input required min="0" type="number" placeholder="Stock" value={form.stock} onChange={e=>setForm(f=>({...f,stock:e.target.value}))} className="input-premium"/><label className="flex items-center gap-2 text-sm text-ink-600"><input type="checkbox" checked={form.organic} onChange={e=>setForm(f=>({...f,organic:e.target.checked}))}/> Organic</label>
      <input required type="url" placeholder="Image URL" value={form.image} onChange={e=>setForm(f=>({...f,image:e.target.value}))} className="input-premium md:col-span-2"/><input placeholder="Description" value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))} className="input-premium md:col-span-2"/><button disabled={saving} className="btn-primary md:col-span-4">{saving?'Saving...':'Add product'}</button></form>{message&&<p className="mt-3 text-sm text-primary">{message}</p>}
    <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="text-left text-xs uppercase text-ink-400"><th className="pb-3">Product</th><th>Stock</th><th>Selling price</th><th>Original price</th><th>Alert</th><th>Action</th></tr></thead><tbody>{products.map(p=><InventoryRow key={p.id} product={p} disabled={saving} onSave={update} onDelete={remove}/>)}</tbody></table></div>
  </section>;
}

function InventoryRow({ product, disabled, onSave, onDelete }: { product: Product; disabled: boolean; onSave: (p: Product, v: { stock:number; price:number; oldPrice?:number })=>void; onDelete: (p: Product)=>void }) {
  const [stock,setStock]=useState(product.stock); const [price,setPrice]=useState(product.price); const [oldPrice,setOldPrice]=useState(product.oldPrice?.toString()??'');
  return <tr className="border-t border-cream-200"><td className="py-3 font-semibold text-ink">{product.name}</td><td><input type="number" min="0" value={stock} onChange={e=>setStock(Number(e.target.value))} className="input-premium w-24"/></td><td><input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))} className="input-premium w-28"/></td><td><input type="number" min="0" step="0.01" value={oldPrice} onChange={e=>setOldPrice(e.target.value)} className="input-premium w-28"/></td><td>{stock===0?<span className="chip bg-error/10 text-error"><AlertTriangle className="h-3 w-3"/>Out of stock</span>:stock<10?<span className="chip bg-warning/10 text-warning"><AlertTriangle className="h-3 w-3"/>Low stock</span>:<span className="text-success">Healthy</span>}</td><td><div className="flex gap-2"><button disabled={disabled} onClick={()=>onSave(product,{stock,price,oldPrice:oldPrice?Number(oldPrice):undefined})} className="rounded-full bg-primary p-2 text-white" aria-label={`Save ${product.name}`}><Save className="h-4 w-4"/></button><button disabled={disabled} onClick={()=>onDelete(product)} className="rounded-full bg-error p-2 text-white" aria-label={`Delete ${product.name}`}><Trash2 className="h-4 w-4"/></button></div></td></tr>;
}
